### ISSUE TITLE
Add more product screenshots/diagrams to UG

### ISSUE THREAD

**Issue by Javiery3889** [AY2324S2-CS2103-F15-1/tp#198]
These are considered UG bugs:

> Not enough visuals e.g., screenshots/diagrams
> The visuals are not well integrated to the explanation
> The visuals are unnecessarily repetitive e.g., same visual repeated with minor changes

Perhaps we can include more screenshots to aid our explanation for the components of our UI

**Comment by KohGuanZeh** [comment]
May want to include screenshot of successful command output and command errors.
