### ISSUE TITLE
[PE-D][Tester B] deletetag command on UG should specify that it is case-sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-1/tp#223]
Since the find command is case-insensitive, it would be good to state that deletetag command is case-sensitive in the UG such that to delete a tag, the user inputted tag must match the tag to be deleted exactly.

![image.png](https://raw.githubusercontent.com/qinboan/ped/main/files/0aab8ba3-61c8-4e6c-8105-1e58af29c228.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: qinboan/ped#2

**Comment by Dethada** [comment]
This is stated in the UG
