### ISSUE TITLE
[PE-D][Tester E] Lack of visuals in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-1/tp#224]
## Describe the bug
No features in the UG have any visual aids in explanation except the `help` command. Visual aids would be useful for example for showing how the gui is supposed to look after scheduling a meeting for today

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: yashpola/ped#5

**Comment by Dethada** [comment]
Duplicate of #229
