### ISSUE TITLE
[PE-D][Tester D] Address should allow '@'

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-1/tp#235]
![Screenshot 2024-04-05 at 5.06.57 PM.png](https://raw.githubusercontent.com/sethteo/ped/main/files/44f67d60-ec9d-4b97-991c-a2305dffe408.png)

Its nice that you allowed for typical special characters in your address however with Singaporean condos and even HDBs adding '@' to their name I think that character should be allowed as well :)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: sethteo/ped#7

**Comment by Javiery3889** [comment]
Will be adding this to the "Planned Enhancement" in our UG.

See Prof's reply in: https://github.com/nus-cs2103-AY2324S2/forum/issues/692
