### ISSUE TITLE
[PE-D][Tester B] Removing the remark from a person

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-1/tp#242]
Removing a remark from a person puts "-" in the person. However, removing a meeting remark removes the meeting remark completely. 

It would be good to either remove the remark completely or put "Remark: " instead of just "-".

This is a purely cosmetic problem.

![image.png](https://raw.githubusercontent.com/qinboan/ped/main/files/9e5168b3-291f-4572-b472-00a492043ec7.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: qinboan/ped#8

**Comment by Dethada** [comment]
Just a difference in design choice
