### ISSUE TITLE
[PE-D][Tester B] Not more than 1 meeting can be scheduled for any contact

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-1/tp#250]
Only allowing to schedule 1 meeting per contact might cause inconvenience to users as many people might want to schedule more than 1 meeting. For example, a weekly meting for a school project.

![image.png](https://raw.githubusercontent.com/qinboan/ped/main/files/4f229b1e-b01e-4d2d-ae39-97a6ad94a096.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: qinboan/ped#12

**Comment by Dethada** [comment]
Our target users are financial advisors whose usual workflow is to schedule one meeting with a client then reschedule the next one if needed.
