### ISSUE TITLE
[PE-D][Tester A] Possible typo in reschedule error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-1/tp#255]
![image.png](https://raw.githubusercontent.com/dillontkh/ped/main/files/2a80b4c0-d6d9-40bb-9884-23bb34f96f13.png)

Following the format `dd-MM-yyyy'T'HH:mm` given in the response message results in an invalid command.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: dillontkh/ped#14

**Comment by Dethada** [comment]
The single quotes are added to separate the delimiter `T` from the datetime values. It should be clear enough with the example behind.
