### ISSUE TITLE
Update instructions for manual testing in DG

### ISSUE THREAD

**Issue by Arixeyeion** [AY2324S2-CS2103-F15-1/tp#298]
- [x] Launching of Application
- [x] Add Command
- [x] List Command
- [x] Edit Command
- [x] Find Command
- [x] Delete Command
- [x] Schedule Command (@YuZizhen )
- [x] Unschedule Command (@YuZizhen )
- [x] Reschedule Command (@Dethada )
- [x] Remark Command
- [x] Add Tag Command (@Arixeyeion )
- [x] Delete Tag Command (@Arixeyeion )
- [x] Clear Command
- [x] Exit Command
- [x] Help Command

Let's try to follow this in order which is the sequence in our UG.

**Comment by Javiery3889** [comment]
Closed in #330
