### ISSUE TITLE
Update javadoc for `meeting` class

### ISSUE THREAD

**Issue by Arixeyeion** [AY2324S2-CS2103-F15-1/tp#84]
Right now the javadoc for meeting reflects Address and email instead of meeting.

**Comment by Dethada** [comment]
Specifically these,
https://github.com/AY2324S2-CS2103-F15-1/tp/blob/016c941487cb03aaeb0d0dc77ddbfd0ae99d3a63/src/main/java/seedu/findvisor/model/person/Meeting.java#L26-L31

https://github.com/AY2324S2-CS2103-F15-1/tp/blob/016c941487cb03aaeb0d0dc77ddbfd0ae99d3a63/src/main/java/seedu/findvisor/model/person/Meeting.java#L38-L41
